name: Build and Test

on:
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Test
        run: npm run test:cov

      - name: Report Coverage
        if: always() # Generate the report even if tests are failing
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all
